version: '3.8'
services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '8081:8080'
    depends_on:
      - db
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    env_file:
      - .env
    depends_on:
      - db
    networks:
    - dev-network

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    networks:
      - dev-network

  minio:
    image: minio/minio
    ports:
      - "${MINIO_API}:${MINIO_API}"
      - "${MINIO_PORT}:${MINIO_PORT}"
    env_file:
      - .env
    volumes:
      - ~/docker/minio-data:/data
    command: server --console-address :${MINIO_PORT} /data
    networks:
      - dev-network

volumes:
  db-data: {}

networks:
  dev-network:
    driver: bridge